### PR TITLE
add slot for additional content, improve css flexibility

### PR DESCRIPTION
**Pull request by mkazlauskas**

### CODE REVIEW

**Comment by nidelson** [comment]
I really enjoyed the possibility of having an action button on this component!
Congratulations @mkazlauskas for the PR!
However, according to specification, it can not be any additional content whatsoever. The snackbar can have only one message and optionally one action button.
So, I think in the place of the slot should have explicitly a button can be set the action as needed. If no action and label provided for it, the button would be hidden by default.
For some time I've been looking for a component that follows the specifications correctly. I even started mine, but this one is ball sho. Just missing the same actions!
Congratulations @rene-lindner-isw for the super snackbar!

**Comment by mkazlauskas** [comment]
@nidelson I'm glad you liked it. I can replace the slot with a button and action properties. The styling can be taken care of by paper elements css properties and mixins, so it works for me. For the most part. I'd like to be able to use a paper-icon-button as the action button too. How would that play with snackbar spec and scope of this element?

**Comment by nidelson** [comment]
@mkazlauskas  I also think it would look more beautiful and intuitive!
However, it should be a simple paper-button, because the specification claims to be a single line of text and can not contain icons. The same goes for the buttons.
- The buttons should only be upper case text.
- Default color of the button text in yellow (# f4cb1e).

If you want to add something to the user, you can customize the colors of the buttons, for example, a green one confirming that it worked or red signaling that there was a failure.

The simple and intuitive is what makes the difference.

Take a look at this link:
Https://material.io/guidelines/components/snackbars-toasts.html

**Comment by nidelson** [comment]
Honestly ... I think only the slot is good. It will allow expansion and resolve the lack of action buttons. Neither paper-toast (https://www.webcomponents.org/element/PolymerElements/paper-toast/elements/paper-toast) is so perfect. Even it has a slot allowing you to add whatever you want. Whoever follows the pattern, will add a button and action.

**Comment by mkazlauskas** [comment]
@nidelson I agree slot is a good option. However, there are advantages of having predefined action button other than forcing compliance to spec: I think it would be easier to manage multiple types of actions (sure, with slot you could handle it in snackbar's parent element, but it's not very convenient). Either way for this we'd probably need to implement remote notifications, e.g. dispatch an "action" event to the opener remote.

On button colors: if we do a predefined button, we can make styling easier by adding an additional 'type' attribute to snackbar invocation params, and then have some predefined types (e.g. success, error), which will apply a class that applies text color from css variable.

I'm interested in what @rene-lindner-isw has to say on this.

**Comment by rene-lindner-isw** [comment]
Thanks for the PR, looks pretty awesome so far!

Though i dislike the idea of putting an action button directly to the snackbar, you can't control it individually for each remote.

My future plans for an action button are to make them controllable through the remote, something like
```
<isw-snackbar-remote message="I have an action button" action-button="I do something" on-action-tap="_actionWasTapped"></isw-snackbar-remote>
```

So i can't merge this PR as it is now, sry, but may i ask you for crafting an new PR with the css Parts only? Would highly appreciate it :)

For the action button, we don't really need it for our use case, so i can't implement it in work time, but if i find some time in the weekend i'll have a look on this :)

**Comment by mkazlauskas** [comment]
It has literally 3 lines of code on css so feel free to copy over when you do some work on this element.

I can do the remote actions for you, but in addition to your sample properties I need to be able to style the button from the remote (or have predefined types). How about having an additional "snackbar-class" property on the remote? It would set class on `isw-snackbar`, therefore allowing me to switch between different css variables.

**Comment by rene-lindner-isw** [comment]
Regarding the button, i would add an static paper-button.
If a slot would be used, it has to be on the remote for flexibility, making the element a lot more complex.

Any other button would be not MD conform anyway.

To the color, technically something like that would be possible.
```
<isw-snackbar-remote message="I have an action button" action-button="I do something" on-action-tap="_actionWasTapped" action-button-color="#333333"></isw-snackbar-remote>
```
Maybe it would be even possible to read an custom css property from the remote and forward it to the snackbar.

**Comment by rene-lindner-isw** [comment]
Hm the class approach you descriped is interesting too.
Will think about it.

**Comment by mkazlauskas** [comment]
Even though `action-button-color` would be enough for me I don't see any benefits over class. Color vs class is like <style> vs style="", but constrained to a single css property.

As an added benefit to using class approach you could dynamically style other parts of the snackbar, even without action-button.

**Comment by rene-lindner-isw** [comment]
Hm. For now my favoured strategy would be to add an set of custom css propertys to the remote, and send them with the open event to the snackbar. Would be the most "polymer intuitive" way.

But i have to try it, as i wrote above i'm not 100% sure it's possible.

**Comment by mkazlauskas** [comment]
I like the idea of delegating css properties. It should be possible:

**Comment by rene-lindner-isw** [comment]
Just read the same. Think we should move this to your issue. Will create an issue for the action button.

**Comment by mkazlauskas** [comment]
Can you reopen this? I've implemented action button. Will do basic styling stuff too.

**Pull request closed without merging**
